### ISSUE TITLE
 Setctty set but Ctty not valid in child

### ISSUE THREAD

**Issue by introspection3** [JiangKlijna/web-shell#10]
linux arm & amd 64bit

your realse binary

maybe: your release version is too old,with low pty version

**Comment by introspection3** [comment]
@ddevault如果要在子进程中打开，则它在子进程中必须具有文件描述符。当按照 creack/pty 代码使用时，必须在 or 或 or 或 .如果它不在其中任何一个，那么当子进程运行时，它将关闭。如果它位于其中之一中，则为您提供应在 中使用的文件描述符编号。ttyos/exec.CmdttyStdinStdoutStderrExtraFilesCtty

现在，吱吱作响的代码正在设置为父级的文件描述符编号。这是偶然工作（假设它正在工作）。正确的解决方法是确保将其传递给子项的某处，并设置为适当的描述符编号。如果可以设置所有 、 ，最简单的方法是始终将 添加到 并设置为 。这将适用于旧版本的 Go 以及即将发布的 1.15 版本。CttyttyCttyStdinStdoutStderrttyExtraFilesCtty3

**Comment by JiangKlijna** [comment]
The v1.0 version does have this bug
But This bug has been fixed in v2.0 branch
For details, see this pr #3
