### ISSUE TITLE
can not fork shell

### ISSUE THREAD

**Issue by karma-sun** [JiangKlijna/web-shell#2]
command to start server:
web-shell -s -cmd bash

in browser, after login,it report a error "fork/exec /usr/bin/bash: Setctty set but Ctty not valid in child"

**Comment by JiangKlijna** [comment]
Honestly, I don't know what the problem is, but you can go to [go-console](https://github.com/runletapp/go-console) to find the answer.

**Comment by shanjunmei** [comment]
upgrade the dependency
