### ISSUE TITLE
Stateless session mechanism is non-standard and uses insecure cryptographic functions

### ISSUE THREAD

**Issue by twitchyliquid64** [JiangKlijna/web-shell#4]
See: https://github.com/JiangKlijna/web-shell/blob/ebd1b450cb25b282cb3dd5939afeb88b2974179f/lib/generate.go

This is extremely scary from a security perspective, and rather unnecessary (could be done securely + easily with PASETO tokens like https://github.com/aidantwoods/go-paseto).

Would you accept a PR to switch the login logic to use PASETO?

**Comment by JiangKlijna** [comment]
Of course, I'm glad to accept.
