### ISSUE TITLE
 http: panic serving [::1]:55044: Failed to load winpty.dll: The specified module could not be found.

### ISSUE THREAD

**Issue by introspection3** [JiangKlijna/web-shell#6]
http: panic serving [::1]:55044: Failed to load winpty.dll: The specified module could not be found.

**Comment by JiangKlijna** [comment]
windows need https://github.com/rprichard/winpty/releases/tag/0.4.3
Please put the files winpty.dll into the project root directory

**Comment by JiangKlijna** [comment]
1.  I have developed a method to download winpty.dll, execute `make winpty` in command line, it will download winpty.dll (in v2.0 branch).
2.  I don't think we should put winpty.dll in the web-shell project, because web-shell is not just a windows project.
