### ISSUE TITLE
there is something wrong with your v2.0 code

### ISSUE THREAD

**Issue by introspection3** [JiangKlijna/web-shell#8]
use this on windows os
  web-shell -s -P 2020 -u admin -p admin -cmd cmd
  
  but tell us :enter password...........

**Comment by JiangKlijna** [comment]
[This bug has been fixed in the v2.0 branch](https://github.com/JiangKlijna/web-shell/commit/00a1169bb08e68b6711e91f3f0d52a6d30bce1d7)
